name: PR Commit
on:
  pull_request:
    branches: [main]
env:
  WORKSPACE_ROOT: .

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.4
      - name: Set up NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Lint source code
        run: npm run lint
      - name: Lint commits
        run: npx commitlint --verbose --from=origin/main

  check-format:
    name: Check Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.4
      - name: Set up NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Check code format
        run: npm run format:check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    env:
      FLOW_CLI_VER: v0.41.0
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.4
      - name: Set up NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Install Flow CLI
        run: |
          curl -fsSL https://storage.googleapis.com/flow-cli/install.sh | bash -s ${{env.FLOW_CLI_VER}}
          flow version
      - name: Run unit tests
        run: npm run test

  build:
    name: Build library
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.4
      - name: Set up NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Build library
        run: npm run build
